### ISSUE TITLE
Apps link on the FAQ doesn't lead anywhere

### ISSUE THREAD

**Issue by S0ulf3re** [misskey-dev/misskey-hub#107]
[The link](https://misskey-hub.net/en/docs/faq.html#are-there-any-apps-for-ios-android-available) in the Frequently asked questions page for Misskey apps currently leads to a 404 error. Which is a shame because I'm really wanting to know which apps are available for Misskey.

**Comment by sei0o** [comment]
I use [Milktea](https://github.com/pantasystem/Milktea) on Android. [Kaiteki](https://github.com/Kaiteki-Fedi/Kaiteki) also looks promising. I have to admit there are lots of broken links and immature docs.

**Comment by S0ulf3re** [comment]
I mainly came to it looking for iOS clients. I can't seem to really find any around beyond Misscat, which is in Japanese and also hasn't been updated recently. May have to take matters into my own hands

**Comment by sei0o** [comment]
SocialHub for iOS supports Misskey and seems to be maintained.
