### ISSUE TITLE
Translation Contribution

### ISSUE THREAD

**Issue by pchxyz** [misskey-dev/misskey-hub#127]
In order to better promote Misskey to Taiwanese, I'd like to contribute with Tradtional Chinese translation. How can I do it? By uploading translated files?

**Comment by sei0o** [comment]
You might be interested in taking a look at #114, which includes Italian translations. `src/.vuepress/config.ts` and `src/(lang)/README.md` seem to be good starting places.

**Comment by pchxyz** [comment]
I read it before openning this issue but I've never done a commit and PR, I'lll try to figure it out. Thanks for the head up!
