### ISSUE TITLE
トップページの ≡ を押してもメニューが表示されない

### ISSUE THREAD

**Issue by fu-sen** [misskey-dev/misskey-hub#141]
https://misskey-hub.net/ トップページ部分をスマートフォンなど、横幅が狭い状態で表示した時に左上に表示されている **≡** が表示されますが、これを押してもメニューが表示されません。中の各ページでは正常に機能しているように見えます。

参考:
https://misskey.io/notes/99p986af2a

**Comment by sei0o** [comment]
related: #125

**Comment by tamaina** [comment]
Duplicate od https://github.com/misskey-dev/misskey-hub/issues/125
