### ISSUE TITLE
プロフィールのハッシュタグリンクの挙動がおかしい

### ISSUE THREAD

**Issue by Apricot-ale** [misskey-dev/misskey-hub#198]
プロフィールのハッシュタグをクリックした際、リンク先のアドレスが
`https://misskey.io/tags/Misskey` となるべきが
`https://misskey.io/explore/tags/Misskey` となってしまう

環境
OS: Win10
ブラウザ: Edge
プラグイン無し

**Comment by syuilo** [comment]
こちら正しい挙動になります

**Comment by Apricot-ale** [comment]
仕様の件了解しました
