### ISSUE TITLE
利用者向けマニュアルの拡充（投稿画面で画像にNSFW設定を行う）

### ISSUE THREAD

**Issue by mappi-pr** [misskey-dev/misskey-hub#270]
- 画像に対して、なぜかNSFWが自動判定されているように見えるが何が起きているかわからない
	- （「センシティブなメディアの検出」機能があることが利用者に伝わっていなさそう）
-  投稿画面において、添付した画像のオンオフを手動で切り替えを行いたいが、実際の操作方法がわからない

といった、ノートを見かけたので
Misskey-Hubにおいても利用者向けのマニュアルを
拡充したほうがよいのではないかと思いました。

本Issueでは、
1. 投稿画面で画像にNSFW設定を行う手順の説明の追記
2. サーバによっては「センシティブなメディアの検出」機能がONになっていることの追記

について、提案をしたいです。

**Comment by kakkokari-gtyih** [comment]
https://github.com/misskey-dev/misskey/pull/12141 で本家のセットアップ時チュートリアルに実装しました

**Comment by mappi-pr** [comment]
本家のチュートリアルに実装されたのでクローズします
