### ISSUE TITLE
Issue during install?

### ISSUE THREAD

**Issue by iceguru** [misskey-dev/misskey-hub#89]
`ice@nobody-hq:~/misskey$ sudo docker-compose run --rm web yarn run init
Creating misskey_web_run ... done
yarn run v1.22.17
$ npm run migrate

> misskey@12.110.1 migrate
> cd packages/backend && npx typeorm migration:run -d ormconfig.js

Error during migration run:
Error: Unable to open file: "/misskey/packages/backend/ormconfig.js". bad indentation of a mapping entry (52:4)

 49 | 
 50 |   # Extra Connection options
 51 |   #extra:
 52 |    ssl: true
---------^
 53 | 
 54 | #   ┌─────────────────────┐
    at Function.loadDataSource (/misskey/packages/backend/node_modules/typeorm/commands/CommandUtils.js:22:19)
    at async Object.handler (/misskey/packages/backend/node_modules/typeorm/commands/MigrationRunCommand.js:34:26)
npm notice 
npm notice New minor version of npm available! 8.3.1 -> 8.10.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.10.0
npm notice Run npm install -g npm@8.10.0 to update!
npm notice 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: 1
ice@nobody-hq:~/misskey$ npm -v
8.10.0
`

**Comment by 4ioskd** [comment]
If you encoutered a problem during install misskey, at first, please ask it on Misskey Official Discord( https://discord.gg/Wp8gVStHW3 ) or Misskey Forum( https://forum.misskey.io ). Even if you ask it on these places and can' solve your installation problem, making an issue on misskey-dev/missky repository( https://github.com/misskey-dev/misskey ) is recommended.
This repo is specialized for Misskey-hub( Misskey Official Website ).
