### ISSUE TITLE
https://misskey-hub.net/ns にちゃんとMisskey独自拡張系オプションの説明を置く

### ISSUE THREAD

**Issue by rinsuki** [misskey-dev/misskey-hub#96]

**Comment by rinsuki** [comment]
というかそもそも /ns でちゃんと `application/ld+json` を返すべきか

**Comment by Johann150** [comment]
> というかそもそも /ns でちゃんと `application/ld+json `を返すべきか

I think that would be required if we used it like this:
```json
{
  "@context": [
    "https://misskey-hub.net/ns"
  ]
}
```

But as far as I know we are using it like this instead, in which case I do not think it makes sense to return JSON-LD, because the URLs are only used to be unique.

```json
{
  "@context": [
    {
      "misskey": "https://misskey-hub.net/ns#",
      "isCat": "misskey:isCat"
    }
  ]
}
```

(All examples are of course only shortened versions.)

**Comment by Johann150** [comment]
Should the page at `https://misskey-hub.net/ns` be in English or in Japanese? I'm not sure because Misskey's primary language is Japanese, but more people might be able to understand English better.
